# https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html
executor: slurm
jobs: 10

software-deployment-method:
  - conda
  - apptainer
apptainer-args: "--bind /scratch/sbuedenb --nv"
conda-prefix: /scratch/sbuedenb/snakemake


default-resources:
    slurm_partition: "gpu"
    slurm_account: "ag-wiehe"
    mem: "64gb"
    runtime: 60
