# look at ncbi ftp links to find new urls
FASTA_URL: {
  "GCF_000001735.4": "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.fna.gz"
}

MODELS: [
    "gonzalobenegas/gpn-brassicales",
]

SEQUENCES: [
    "GCF_000001735.4",
]

DISPLAY_VMAX: 3

CHROMOSOME: "NC_003076.8"
START_POSITION: 6484798
END_POSITION: 6485309

DISPLAY_MAP_START_RELATIVE: 384
DISPLAY_MAP_END_RELATIVE: -64