# look at ncbi ftp links to find new urls
FASTA_URL: {
  "GCF_000001735.4": "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.fna.gz"
}

MODELS: [
    "gonzalobenegas/gpn-brassicales",
]

SEQUENCES: [
  "NC_003076.8"
    # "GCF_000001735.4",
    # "Lan3.1"
]

DISPLAY_VMAX: 1.5

CHROMOSOME: "NC_003076.8"
START_POSITION: 10000
END_POSITION: 11000


# fuer yannick
# HMA4-1 chr3 22023391-22031473
# HMA4-2 chr3 21941657-21950203
# HMA4-3 chr3 21886677-21896021
# CHROMOSOME: "chr3"
# START_POSITION: 22023391
# END_POSITION:   22031473
# START_POSITION: 21941657
# END_POSITION:   21950203
# START_POSITION: 21886677
# END_POSITION:   21896021


DISPLAY_MAP_START_RELATIVE: 0
DISPLAY_MAP_END_RELATIVE: -1